# Generated by Django 4.2 on 2023-04-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_pseudo', models.CharField(max_length=50)),
                ('admin_password', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=70)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_category', models.CharField(max_length=70)),
                ('product_gender', models.CharField(max_length=20)),
                ('product_promoted', models.BooleanField(default=False)),
                ('product_promotion_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product_promotion_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_promotion_end_date', models.DateField()),
                ('product_picture', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
    ]
