# Generated by Django 4.2 on 2023-04-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0005_gender_alter_product_product_price_delete_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_picture',
            field=models.ImageField(upload_to='appli/static/img/uploads/'),
        ),
    ]
