# Generated by Django 4.2 on 2023-04-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0007_alter_product_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_picture',
            field=models.ImageField(upload_to='appli/static/appli/img/upload/'),
        ),
    ]
