# Generated by Django 4.2 on 2023-04-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0010_alter_product_product_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizePants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SizeShoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SizeStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('display_order', models.SmallIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_sizes',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.AddField(
            model_name='product',
            name='product_size_pants',
            field=models.ManyToManyField(blank=True, to='appli.sizepants'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_size_shoes',
            field=models.ManyToManyField(blank=True, to='appli.sizeshoes'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_size_standard',
            field=models.ManyToManyField(blank=True, to='appli.sizestandard'),
        ),
    ]
