# Generated by Django 4.2 on 2023-04-12 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0011_sizepants_sizeshoes_sizestandard_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SizePants',
            new_name='SizePant',
        ),
        migrations.RenameModel(
            old_name='SizeShoes',
            new_name='SizeShoe',
        ),
    ]
