# Generated by Django 4.2 on 2023-04-16 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0012_rename_sizepants_sizepant_rename_sizeshoes_sizeshoe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
