# Generated by Django 4.2 on 2023-04-23 10:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0013_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_promotion_price',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_picture',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
