# Generated by Django 4.2 on 2023-04-23 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0014_remove_product_product_promotion_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_size_pants__title']},
        ),
    ]
