# Generated by Django 4.2 on 2023-04-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0015_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterField(
            model_name='product',
            name='product_picture',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
