# Generated by Django 4.2 on 2023-04-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0019_alter_product_product_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_promotion_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_picture',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
