# Generated by Django 4.2 on 2023-04-25 19:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0020_product_product_promotion_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_picture',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
